### ISSUE TITLE
commands not being placed into PATH

### ISSUE THREAD

**Issue by grburgess** [fermi-lat/pyBurstAnalysisGUI#3]
Hi! I've found what might be a bug in the conda distribution related to the commands. 

When running the scripts for unbinned GRB analysis, the downloader script (for example) is being called but it is not in the PATH, so the popen command fails. If one were to install this manually, then you would need to put <>/lib/python2.7/site-packages/fermitools/GtBurst/commands/ in your PATH and then it works as predicted.

However, I was under the impression that this should be done automatically with the conda install such that

PATH=${CONDA_PREFIX}/lib/python2.7/site-packages/fermitools/GtBurst/commands/:${PATH}

but this is not the case. 

It is, of course, easy to do this, but it might be useful to have it done upon install and activation of the conda environment as it is not transparent where these scripts are in the library and users might not be able to figure it out on their own.

Thanks!

**Comment by jasercion** [comment]
I'll incorporate this update into our next release builds.  Thanks!

**Comment by jasercion** [comment]
Added in commits [c90b3eb](https://github.com/fermi-lat/Fermitools-conda/commit/c90b3eba5de5736a31e6f736d9e71d22677a0227) and [176063b](https://github.com/fermi-lat/Fermitools-conda/commit/176063bd76a744ada908ec7e1fb32ba0e1a7f9ca)

**Comment by grburgess** [comment]
Thanks!

**Comment by jasercion** [comment]
Hi @grburgess.  The changes are incorporated into alpha build Fermitools=1.1.3.  If you'd like to test them out you can install that version with the command

`conda install -c conda-forge/label/cf201901 -c fermi/label/alpha -c fermi fermitools=1.1.3`

Please note that because this version is still in testing we can't officially support it at this time.  Since the fix is now in the build I'm closing out the issue, but please reopen it if you find the problem persists.
